// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZotnDvIWebxMUnuJqmPQhG7v5BhOA4q4',
    appId: '1:465520690779:web:41f293c729ee78f9c3617e',
    messagingSenderId: '465520690779',
    projectId: 'padur-library-58b3a',
    authDomain: 'padur-library-58b3a.firebaseapp.com',
    storageBucket: 'padur-library-58b3a.firebasestorage.app',
    measurementId: 'G-S42468EJ26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbmD9X3PjWdaaGjN6L2xBj7GGwaTet_a0',
    appId: '1:465520690779:android:2f918fea90acd3dcc3617e',
    messagingSenderId: '465520690779',
    projectId: 'padur-library-58b3a',
    storageBucket: 'padur-library-58b3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7zTIlm5vnkSDytHxBD0e846Cee9U1MwY',
    appId: '1:465520690779:ios:aeaa870368971c98c3617e',
    messagingSenderId: '465520690779',
    projectId: 'padur-library-58b3a',
    storageBucket: 'padur-library-58b3a.firebasestorage.app',
    iosBundleId: 'com.example.adminApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7zTIlm5vnkSDytHxBD0e846Cee9U1MwY',
    appId: '1:465520690779:ios:aeaa870368971c98c3617e',
    messagingSenderId: '465520690779',
    projectId: 'padur-library-58b3a',
    storageBucket: 'padur-library-58b3a.firebasestorage.app',
    iosBundleId: 'com.example.adminApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZotnDvIWebxMUnuJqmPQhG7v5BhOA4q4',
    appId: '1:465520690779:web:8ca2640c2107803ec3617e',
    messagingSenderId: '465520690779',
    projectId: 'padur-library-58b3a',
    authDomain: 'padur-library-58b3a.firebaseapp.com',
    storageBucket: 'padur-library-58b3a.firebasestorage.app',
    measurementId: 'G-DY5SWDBBEF',
  );
}
